### ISSUE TITLE
After installing NDK tests don't run

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo-executor#15]
All builds with tests fail after installing NDK.

06:33:53  * What went wrong:
06:33:53  Execution failed for task ':main:installBasicDebug'.
06:33:53  > com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /opt/android-sdk-linux/platform-tools/adb
06:33:53  
06:33:53  * Try:
06:33:53  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I temporary started old ones.
@kumy and ideas?

**Comment by mucek4** [comment]
From log when starting.
```
2020-02-28 05:59:53,755 INFO spawned: 'android' with pid 114
2020-02-28 05:59:53,777 INFO exited: android (exit status 127; not expected)
2020-02-28 05:59:56,598 INFO spawned: 'android' with pid 125
2020-02-28 05:59:56,627 INFO exited: android (exit status 127; not expected)
2020-02-28 06:00:00,159 INFO spawned: 'android' with pid 136
2020-02-28 06:00:00,183 INFO exited: android (exit status 127; not expected)
2020-02-28 06:00:01,184 INFO gave up: android entered FATAL state, too many start retries too quickly
```

**Comment by kumy** [comment]
@mucek4 log into the container and launch the emulator manually to get the exact error. I remember I had problem with `/dev/kvm` permissions in the past.

**Comment by mucek4** [comment]
Found it. KVM permissions should be solved with script.
```
/opt/android-sdk-linux/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
```

**Comment by mucek4** [comment]
Hm. Image rebuilded. Now we get different error. @kumy ?

```
2020-02-28 10:08:57,990 INFO spawned: 'android' with pid 140
2020-02-28 10:08:59,396 INFO success: android entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-28 10:08:59,923 INFO exited: android (terminated by SIGABRT (core dumped); not expected)
```

```
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
```

**Comment by kumy** [comment]
Never seen that :/ is there new option to have the emulator running headless?

**Comment by mucek4** [comment]
We already run it with `-no-window` option.

**Comment by mucek4** [comment]
@kumy I have tried many things. With no success. Newer version of Ubuntu, older version of ADT, installed several libraries I found on internet that shall work. Can you take a look if you find more luck? I added `libxcomposite1 libxcursor1` to apt-get install and then missing libraries are ok.

**Comment by kumy** [comment]
I'm not available this week end :(

**Comment by mucek4** [comment]
No problem. I was also off. Currently we run executor 4 and 5 on old image and executor 3 on new image. Executor 1 and 2 are free for testing.

**Comment by Lineflyer** [comment]
For the records:

From @mucek4:
When we added 2 libraries to CI for whereyougo it failed to start emulator. Therefore 3 is not running emulators and 4 and 5 are running old Docker Image. I think I asked @kumy to look at it.
c:geo build shall not run on emulator 3

**Comment by Lineflyer** [comment]
From @Lineflyer:
OK, I set the option to reserve "cgeo-3" exclusively for bound projects. So I guess cgeo-3 should now no longer be used for cgeo CI-builds although it has the attribute "has-emulator".

**Comment by Lineflyer** [comment]
FYI:
"cgeo-3" was still used for CI and PR builds.
I did now temporarily remove the label "has-emulator" from the slave configuration. Hope this helps.

**Comment by mucek4** [comment]
Hey. I have just pushed an [updated version](https://github.com/cgeo/cgeo-executor/commit/014fca3033bb4139c206d773198c8cd943cfc1fd). executor 1 is running this setup for a week, I'll update 4 and 5 today.
