### ISSUE TITLE
missing build tools 23.0.3 in image

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo-executor#6]
From PR https://github.com/cgeo/cgeo/pull/5597

Our image doesn't contain `build tools 23.0.3`

**Comment by kumy** [comment]
1. I've created a jenkins [job](http://ci.cgeo.org/view/Executors/job/Upgrade%20SDK/) to update running executors
2. maybe we should add `android-23` to the filter

**Comment by kumy** [comment]
@samueltardieu may you please update your image?
`android-accept-licenses.sh  "android update sdk -u --all --filter android-23,build-tools-23.0.3"`

**Comment by kumy** [comment]
@samueltardieu maybe @mucek4 also need to install new build tools to build nightly builds?

**Comment by samueltardieu** [comment]
Ok on my side. @mucek4, can you update your machine?

**Comment by kumy** [comment]
ping @mucek4

**Comment by mucek4** [comment]
Installed
