### ISSUE TITLE
Need to upgrade build-tools and add tools

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo-executor#9]
As required for https://github.com/cgeo/cgeo/pull/6382, let's add `tools`, and upgrade `build-tools` to at least 25.0.0

**Comment by Bananeweizen** [comment]
The upgrade will lead to a new warning for every module:
00:19.545  NDK is missing a "platforms" directory.
00:19.545  If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /opt/android-sdk-linux/ndk-bundle.
00:19.545  If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Can be seen in http://ci.cgeo.org/job/cgeo%20pull%20request/770/console. I guess you might be able to suppress it by already setting that variable, or by installing the NDK (which we don't need).

**Comment by kumy** [comment]
@Bananeweizen the NDK error should be fixed by updating out build.gradle. See: https://github.com/cgeo/cgeo/pull/6383
